// Fixture data for testing lyricsnmusic.js
export const data = [
  {
    'context': null,
    'instrumental': false,
    'snippet': 'Bones sinking like stones \r\nAll that we\'ve fought for \r\nHomes, places we\'ve grown \r\nAll of us are done for \r\n\r\nWe live in a beautiful world \r\nYeah we ...',
    'title': 'Don\'t Panic',
    'url': 'http://www.lyricsnmusic.com/coldplay/don-t-panic-lyrics/4294612',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': false,
    'snippet': 'So I look in your direction\r\nBut you pay me no attention, do you\r\nI know you don\'t listen to me\r\n\'Cause you say you see straight through me, don\'t you...',
    'title': 'Shiver',
    'url': 'http://www.lyricsnmusic.com/coldplay/shiver-lyrics/4294613',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': false,
    'snippet': 'I awake to find no peace of mind\r\nI said how do you live as a fugitive\r\nDown here where I cannot see so clear\r\nI said, what do I know\r\nShow me the rig...',
    'title': 'Spies',
    'url': 'http://www.lyricsnmusic.com/coldplay/spies-lyrics/4294614',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': false,
    'snippet': 'Did I drive you away\r\nI know what you\'ll say\r\nYou say, oh, sing one we know\r\nBut I promise you this\r\nI\'ll always look out for you\r\nThat\'s what I\'ll do...',
    'title': 'Sparks',
    'url': 'http://www.lyricsnmusic.com/coldplay/sparks-lyrics/4294615',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': false,
    'snippet': 'Oh no I see\r\nA spider web it\'s tangled up with me\r\nAnd I lost my head\r\nThe thought of all the stupid things I said\r\nOh no what\'s this\r\nA spider web an...',
    'title': 'Trouble',
    'url': 'http://www.lyricsnmusic.com/coldplay/trouble-lyrics/4294617',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': null,
    'snippet': 'Stuck in a corner \r\nare monkeys in cages \r\nthat don\'t have a number \r\nto fight one another \r\n\r\nTry t...',
    'title': '1.36',
    'url': 'http://www.lyricsnmusic.com/coldplay/1-36-lyrics/lnm:1760',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': null,
    'snippet': 'She\'s gone 2000 miles, it\'s very far\r\nThe snow came down\r\nGet\'s colder day by day, I miss her\r\n\r\nI h...',
    'title': '2000 Miles',
    'url': 'http://www.lyricsnmusic.com/coldplay/2000-miles-lyrics/lnm:1764',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': null,
    'snippet': 'My song is love\r\nMy song is love, unknown\r\nAnd it goes up\r\nYou don\'t have to be alone\r\n\r\nMy heavy he...',
    'title': 'A Message [2010]',
    'url': 'http://www.lyricsnmusic.com/coldplay/a-message-2010-lyrics/lnm:1762',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': null,
    'snippet': 'My song is love\r\nMy song is love, unknown\r\nAnd it goes up\r\nYou don\'t have to be alone\r\n\r\nMy heavy he...',
    'title': 'A Message [2010]',
    'url': 'http://www.lyricsnmusic.com/coldplay/a-message-2010-lyrics/lnm:1763',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': null,
    'snippet': 'I wanna be bigger, stronger, drive a faster car,\r\n\r\nTo take me anywhere in seconds,\r\n\r\nTo take me an...',
    'title': 'Bigger Stronger',
    'url': 'http://www.lyricsnmusic.com/coldplay/bigger-stronger-lyrics/lnm:109',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': null,
    'snippet': 'I feel safe, I feel warm when you\'re here\r\nThen I do no wrong\r\nI am cured, when I\'m by your side\r\nI\'...',
    'title': 'Careful Where You Stand',
    'url': 'http://www.lyricsnmusic.com/coldplay/careful-where-you-stand-lyrics/lnm:1758',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': null,
    'snippet': 'I feel safe, I feel warm when you\'re here\r\nThen I do no wrong\r\nI am cured, when I\'m by your side\r\nI\'...',
    'title': 'Careful Where You Stand',
    'url': 'http://www.lyricsnmusic.com/coldplay/careful-where-you-stand-lyrics/lnm:1756',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
  {
    'context': null,
    'instrumental': null,
    'snippet': 'It could be worse\r\nI could be alone\r\nI could be locked in here on my own\r\nLike a stone that certainl...',
    'title': 'Crests of Waves',
    'url': 'http://www.lyricsnmusic.com/coldplay/crests-of-waves-lyrics/lnm:1757',
    'viewable': true,
    'artist': {
      'name': 'Coldplay',
      'url': 'http://www.lyricsnmusic.com/coldplay',
    },
  },
];

